/**
 * RequestServiceImpl.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package usmRequestService;

public interface RequestServiceImpl extends java.rmi.Remote {
    public java.lang.String logInToken(java.lang.String artifact) throws java.rmi.RemoteException, usmRequestService.WebServiceException;
    public usmRequestService.SubscriptionDetail getRequestItem(java.lang.String sessionID, int subscriptionDetailID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public java.lang.String logIn(java.lang.String userID, java.lang.String password, java.lang.String businessunit) throws java.rmi.RemoteException, usmRequestService.WebServiceException;
    public void addProcessInstance(java.lang.String sessionID, int requestID, int subscriptionDetailID, java.lang.String processInstanceID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public java.lang.String getSystemFormValue(java.lang.String sessionID, int requestID, java.lang.String formFieldName) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public usmRequestService.SubscriptionDetail[] getRequestItemRow(java.lang.String sessionID, int subscriptionDetailID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void saveRequestItems(java.lang.String sessionID, int requestID, java.lang.String addedOfferings, java.lang.String removedOfferings, java.lang.String addedItems) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public usmRequestService.Request addRequestWithForm(java.lang.String sessionID, java.lang.String requestData, java.lang.String requestValuesData, java.lang.String requestValuesDataType, java.lang.String addedOfferings, java.lang.String addedItems, java.lang.String formValuesData) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void unsetProxy(java.lang.String sessionID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.ContentAccessDeniedException;
    public java.lang.String getPendingActionAssigneesByRequestItemID(java.lang.String sessionID, int requestItemID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void addProcessInstanceToRequestItemOffering(java.lang.String sessionID, int requestID, int subscriptionDetailID, java.lang.String processInstanceID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void updateReservationRequestStatusAndId(java.lang.String sessionId, int requestItemId, int status, java.lang.String extReservationId) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void logOut(java.lang.String sessionID) throws java.rmi.RemoteException;
    public void setProxy(java.lang.String sessionID, java.lang.String proxyUserId, java.lang.String proxyDomainId) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public usmRequestService.Note[] getRequestLevelNotes(java.lang.String sessionID, int requestID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public usmRequestService.RequestResourceItem[] getRequestResources(java.lang.String sessionId, int requestItemId) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public usmRequestService.Request[] getRequestsByFilter(java.lang.String sessionID, usmRequestService.FilterBean[] filterBeanArr) throws java.rmi.RemoteException, usmRequestService.WebServiceException;
    public usmRequestService.TicketRequestItem[] getTicketFromRequestItem(java.lang.String sessionID, java.lang.String persid, java.lang.String refNum, int requestItemID, int requestID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public usmRequestService.Request[] getRequestsByUserID(java.lang.String sessionID, java.lang.String userID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public int getRequestItemStatus(java.lang.String sessionID, int subscriptionDetailID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public int getSubscriptionDetailIDForForm(java.lang.String sessionID, java.lang.String formName, int requestID, int offeringID, int groupID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public usmRequestService.RequestResourceItem addResourceToRequestItem(java.lang.String sessionId, int requestItemId, usmRequestService.RequestResourceItem resourceItem) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void removeResourceFromRequestItem(java.lang.String sessionId, int requestItemId, java.lang.String resourceItemId) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public boolean oblicoreEventHandler(java.lang.String sessionID, java.lang.String eventType, java.lang.Object[] eventData, java.lang.String user, java.util.Calendar date) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public usmRequestService.RequestResourceItem updateRequestResource(java.lang.String sessionId, usmRequestService.RequestResourceItem resourceItem) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.ItemNotFoundException, usmRequestService.ContentAccessDeniedException;
    public void updateReservationEndDate(java.lang.String sessionId, java.lang.String endDate, java.lang.String reservationId) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void addTicketToRequestItem(java.lang.String sessionID, java.lang.String persid, java.lang.String refNum, int requestItemID, int requestID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void addAttachmentLinkToSubscription(java.lang.String sessionId, java.lang.String attachmentId, java.lang.String attachmentFileName, java.lang.String attachmentDesc, java.lang.String attachmentLink, java.lang.String attachmentTimeStamp, int sourceTypeId, java.lang.String sourceObjId, java.lang.String userId) throws java.rmi.RemoteException, usmRequestService.WebServiceException;
    public void addProcessInstanceToRequest(java.lang.String sessionID, int requestID, java.lang.String processInstanceID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public usmRequestService.Request[] getRequestsByAccountID(java.lang.String sessionID, java.lang.String accountID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void updateRequestItemStatus(java.lang.String sessionID, int pendingActionType, int requestItemID, int status) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public usmRequestService.Asset[] getAssetUUIDByRequestItemID(java.lang.String sessionID, int subscriptionDetailID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public usmRequestService.FormElement[] getSystemFormValues(java.lang.String sessionID, int requestID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void addAttachmentToRequestItemWithPath(java.lang.String sessionID, int requestID, int subscriptionDetailID, java.lang.String attachmentName, java.lang.String attachmentDescription, java.lang.String attachmentPath) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public usmRequestService.RateItemModel[] getModelUUIDByRequestItemID(java.lang.String sessionID, int requestItemID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public usmRequestService.Attachment[] getRequestItemAttachments(java.lang.String sessionID, int subscriptionDetailID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public usmRequestService.Attachment[] getRequestLevelAttachments(java.lang.String sessionID, int requestID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void editRequestAttachmentDetails(java.lang.String sessionID, int requestID, java.lang.String attachmentID, java.lang.String attachmentName, java.lang.String attachmentDescription) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public int getRequestOfferingStatus(java.lang.String sessionID, int requestID, int offeringID, int groupID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void unassignModelUUIDFromRateItem(java.lang.String sessionID, int rateItemID, java.lang.String modelUUID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void removeRequestAttachment(java.lang.String sessionID, int requestID, java.lang.String attachmentID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public usmRequestService.RateItemModel[] getModelUUIDByRateItemID(java.lang.String sessionID, int rateItemID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public java.lang.String[] getPendingActionsForRequest(java.lang.String sessionID, int requestID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void addWorkflowPendingAction(java.lang.String sessionID, int requestID, int objectType, int objectID, int objectGroupID, java.lang.String workItemID, java.lang.String processInstanceID, java.lang.String userID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void assignAssetUUIDToRequestItem(java.lang.String sessionID, int requestItemID, java.lang.String assetUUID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public int assignPolicyBasedPendingActions(java.lang.String sessionID, int requestID, int levelNo, int pendingActionType, int requestItemID, int requestItemStatus, java.lang.String workItemID, java.lang.String processInstanceID) throws java.rmi.RemoteException, usmRequestService.WebServiceException;
    public void addProcessInstanceToRequestItem(java.lang.String sessionID, int requestID, int subscriptionDetailID, java.lang.String processInstanceID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void addRequestAttachmentWithPath(java.lang.String sessionID, int requestID, java.lang.String attachmentName, java.lang.String attachmentDescription, java.lang.String attachmentPath) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public usmRequestService.Asset[] getAssetUUIDByRequestID(java.lang.String sessionID, int requestID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void addWorkflowPendingActionWithDesc(java.lang.String sessionID, int requestID, int objectType, int objectID, int objectGroupID, java.lang.String workItemID, java.lang.String processInstanceID, java.lang.String userID, java.lang.String description) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void unassignAssetUUIDFromRequestItem(java.lang.String sessionID, int requestItemID, java.lang.String assetUUID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void assignModelUUIDToRateItem(java.lang.String sessionID, int rateItemID, java.lang.String modelUUID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public usmRequestService.RequestRelationship[] getRequestRelationships(java.lang.String sessionID, usmRequestService.FilterBean[] filterBeanArr) throws java.rmi.RemoteException, usmRequestService.WebServiceException;
    public java.lang.String getDefaultUserForRequestActions(java.lang.String sessionID, java.lang.String businessunit) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public usmRequestService.Note[] getRequestNotes(java.lang.String sessionID, int requestID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void addRequestNote(java.lang.String sessionID, int requestID, java.lang.String noteText, int noteType) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public usmRequestService.SubscriptionDetail[] getRequestItems(java.lang.String sessionID, int requestID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public boolean sendRequestEmail(java.lang.String sessionID, int requestId, boolean includeRequestDetails, java.lang.String emailFromAddress, java.lang.String emailFromName, java.lang.String emailTo, java.lang.String emailCC, java.lang.String emailBCC, java.lang.String emailSubject, java.lang.String emailMessage) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.ItemNotFoundException, usmRequestService.ContentAccessDeniedException;
    public usmRequestService.FormItem saveRequestForm(java.lang.String sessionID, int subscriptionDetailID, java.lang.String formValuesData) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void cancelRequest(java.lang.String sessionID, int requestID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public usmRequestService.FormItem getFormRateItemValues(java.lang.String sessionID, int subscriptionDetailID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void addRequestItemNote(java.lang.String sessionID, int subscriptionDetailID, java.lang.String noteText, int noteType) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public int getRequestStatus(java.lang.String sessionID, int requestID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void updateRequestStatus(java.lang.String sessionID, int requestID, int status) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void updateRequestItemRowStatus(java.lang.String sessionID, int subscriptionDetailID, int status) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void updateRequestOfferingStatus(java.lang.String sessionID, int requestID, int offeringID, int groupID, int status) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public java.lang.String getFormRateItemValue(java.lang.String sessionID, int subscriptionDetailID, java.lang.String formRateItemName) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public java.lang.String getPrimaryServiceDesk(java.lang.String sessionID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public usmRequestService.Note[] getRequestItemNotes(java.lang.String sessionID, int subscriptionDetailID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void addRequestOfferingNote(java.lang.String sessionID, int requestID, int offeringID, int groupID, java.lang.String noteText, int noteType) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public usmRequestService.Note[] getRequestOfferingNotes(java.lang.String sessionID, int requestID, int offeringID, int groupID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void submitRequest(java.lang.String sessionID, int requestID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public usmRequestService.Request[] getRequests(java.lang.String sessionID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void deleteRequests(java.lang.String sessionID, java.lang.String[] requestIDs) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public usmRequestService.Request saveRequest(java.lang.String sessionID, java.lang.String requestData, java.lang.String requestValuesData, java.lang.String requestValuesDataType, java.lang.String addedOfferings, java.lang.String removedOfferings, java.lang.String addedItems) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void saveRequestHeader(java.lang.String sessionID, java.lang.String requestData, java.lang.String requestValuesData, java.lang.String requestValuesDataType) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void takePendingAction(java.lang.String sessionID, int requestID, int objectID, int objectGroupID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, com.ca.usm.soap.axisInterfaces.InvalidUserException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public usmRequestService.Request[] getPendingActions(java.lang.String sessionID, java.lang.String userID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public usmRequestService.Request getRequestHeader(java.lang.String sessionID, int requestID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public java.lang.String assignPendingAction(java.lang.String sessionID, int pendingActionType, int requestItemID, int requestItemStatus, java.lang.String pendingActionUsersOrGroups, java.lang.String pendingActionDescriptions, java.lang.String workItemID, java.lang.String processInstanceID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void returnPendingAction(java.lang.String sessionID, int requestID, int objectID, int objectGroupID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void transferPendingAction(java.lang.String sessionID, int pendingActionType, int requestItemID, java.lang.String assigneeID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void transferPendingActionToUser(java.lang.String sessionID, int requestID, int objectID, int objectGroupID, java.lang.String transferToUserID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void transferPendingActionToGroup(java.lang.String sessionID, int requestID, int objectID, int objectGroupID, java.lang.String transferToGroupID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public void delegatePendingActionToUser(java.lang.String sessionID, int requestID, int objectID, int objectGroupID, java.lang.String delegateToUserID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public usmRequestService.Attachment[] getRequestAttachments(java.lang.String sessionID, int requestID) throws java.rmi.RemoteException, usmRequestService.WebServiceException, usmRequestService.PropertyNotSetException, usmRequestService.InvalidFormatException, usmRequestService.ContentAccessDeniedException, usmRequestService.ItemNotFoundException;
    public long getMaxIdleTimeInMilliSeconds() throws java.rmi.RemoteException;
}
